#=========================
#mailsettings.ini
#外接メール送信_設定用外部定義ファイル
#背景:2026年のOA更改に伴い、外接系でのRPA実行が困難となったことにより作成
#目的:外部へのメール送信処理を行うための設定を記載します
#起動契機:
# ┗ー「UserData\InspectingAndMovingInputData.ps1 - ショートカット」をユーザーが起動
#=========================

[General]
# 送信前の最終確認ダイアログを出すか（true/false）
Confirm=true

# 送信元は一律固定（要件）
# "テストのためメールアドレスはダミーです"
From=sakagami156@kawashin.co.jp

# 必要であれば以下にCCを追加
# Cc=

# 要件：Bccは以下で一律
# "テストのため以下のメールアドレスはダミーです"
Bcc=yamada425@kawashin.co.jp

# 文字コード（プリザンターのCSVがUTF-8想定）
# UTF-8BOM以外の文字コードの場合は処理を行わない
# テスト2025年9月5日完了後削除
# CsvEncoding=UTF8

[Paths]
# ユーザー領域（CSV配置場所／スクリプトAのショートカット実行場所／結果返却先）
UserData=\\goa-mailsv\UserData

# 準備領域（スクリプトAの作業場所）
001_InspectingAndMovingInputData=\\goa-mailsv\001_InspectingAndMovingInputData

# 送信処理領域（スクリプトBの作業場所／JP1から監視）
002_BulkSendingExternalEmails=C:\005_bulkSendingExternalEmails\002_BulkSendingExternalEmails

# ログ格納先（各スクリプトごとの作業場所）
001_InspectingAndMovingInputDataLog=\\goa-mailsv\001_InspectingAndMovingInputData\log
002_BulkSendingExternalEmailsLog=C:\005_bulkSendingExternalEmails\002_BulkSendingExternalEmails\log

# マルチ実行時のログファイルは必要なし2025年9月5日
# 002_BulkSendingExternalEmailsLog_Multi_ScheduleExeLog=C:\005_bulkSendingExternalEmails\002_BulkSendingExternalEmails\Multi_ScheduleExeLog

# バックアップCSVファイル格納場所（処理開始前の完全なバックアップのみ、最新一世代）
CSV_FileBackup=C:\005_bulkSendingExternalEmails\002_BulkSendingExternalEmails\BK

[SMTP]
# 実行によるメール送信経路については、Exchange ServerをSMTPサーバとして指定し、m-FILTERへSMTPリレーすることでメールフィルタリング機能を用いる
# Exchangeの受信コネクタ{ExchangeServer2016_パラメータシート参照(ExchangeサーバのOAセグメントを指定)}

# テストのためlocalhost
Server=goa-mailsv
# 「SMTP サーバ機能」を有効にし、待ち受けポート番号は、現行のメールサーバと同様「25/TCP」とする。
Port=25

# ---------- ファイル種別----------
# ファイルの種別を定義
[KOZA_KAISETSU]
CsvKeyword=口座_メール送信時に使用

[GAKKO_JIFU]
CsvKeyword=学校_メール送信時に使用

[TODOKE_HENKO]
CsvKeyword=届出変更_メール送信時に使用